# Generated by Django 6.0.6 on 2026-06-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_ats_score_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(default=''),
        ),
    ]
