# Generated by Django 6.0.6 on 2026-06-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='Fresher', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Not Disclosed', max_length=100),
        ),
    ]
